NUMPY OBJECTS - integers, floating pt., containers : list, dictoinaries


In [3]:
import numpy as np

In [8]:
a = np.array([0,2,4,10,1,3])
print(a)

[ 0  2  4 10  1  3]


useful bcoz provides memory efficient container with fast numerical operations.

In [10]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [13]:
# 1-D
a = np.array([0,2,3,4,5])
a

array([0, 2, 3, 4, 5])

In [15]:
# 2-D
#   a list of lists
b = np.array([[1,3,5,7],[0,2,4,6,8]])
b

<ipython-input-15-c3be7207ec56>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  b = np.array([[1,3,5,7],[0,2,4,6,8]])


array([list([1, 3, 5, 7]), list([0, 2, 4, 6, 8])], dtype=object)

In [23]:
print("Length of b:", len(b))
print("Length of first list :", len(b[0]))

Length of b: 2
Length of first list : 4


In [27]:
# Q. create array using random
# random - module , rand - function
arr = np.random.rand(5)
arr

array([0.49793453, 0.07323182, 0.8707162 , 0.74265475, 0.70034158])

In [30]:
# Access element as index = 5
arr2 = np.arange(10)
print("Element at 5 index :",arr2[5])

Element at 5 index : 5


In [44]:
# SLICING
arr3 = np.arange(10)
print("The array is : ",arr3)
print("The sliced array is :",arr3[1:8:2]) #[starting index : ending index : step(ignore)]

The array is :  [0 1 2 3 4 5 6 7 8 9]
The sliced array is : [1 3 5 7]


In [45]:
arr = np.array([1,2,3,4])
print("Multiplied",arr*2)

print("Doubled",arr**2) # ** = exponent operator 2^2

print("Scalar",arr+3)

Multiplied [2 4 6 8]
Doubled [ 1  4  9 16]
Scalar [4 5 6 7]


All arithmetic between array is elementwise

In [47]:
b = np.ones(4)+1
print(b)
print(arr-b)
print(arr*b)

[2. 2. 2. 2.]
[-1.  0.  1.  2.]
[2. 4. 6. 8.]


In [49]:
arr4 = np.array([1,4,8,9])

print("Minimum val of array :",arr4.min())

print("Maximum val of array :",arr4.max())

print(arr4.argmin())# index of minimum element

print(arr4.argmax())# index of maximum element

Minimum val of array : 1
Maximum val of array : 9
0
3


**Logical Operations**

In [56]:
print(np.all([True, True, False])) # If all true returns true else returns false.
print(np.all([True, True, True]))

False
True


In [58]:
print(np.any([True, False, False])) # If any of them are true returns true.
print(np.any([False, False, False]))

True
False


**PANDAS**
Pandas is python module that makes data science easy and effective

In [59]:
import pandas as pd

In [60]:
df = pd.read_csv('nyc_weather.csv')

In [70]:
#get dimentions of the table

df.shape   #total number of rows and columns

(31, 11)

In [71]:
#if you want to see initial some rows then use head command (default 5 rows)
df.head()

EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
0  1/1/2016           38        23        52                 30.03   
1  1/2/2016           36        18        46                 30.02   
2  1/3/2016           40        21        47                 29.86   
3  1/4/2016           25         9        44                 30.05   
4  1/5/2016           20        -3        41                 30.57   

   VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover Events  \
0               10           8.0               0           5    NaN   
1               10           7.0               0           3    NaN   
2               10           8.0               0           1    NaN   
3               10           9.0               0           3    NaN   
4               10           5.0               0           0    NaN   

   WindDirDegrees  
0             281  
1             275  
2             277  
3             345  
4             333

In [75]:
#if you want to see all columns
df.columns

Index(['EST', 'Temperature', 'DewPoint', 'Humidity', 'Sea Level PressureIn',
       'VisibilityMiles', 'WindSpeedMPH', 'PrecipitationIn', 'CloudCover',
       'Events', 'WindDirDegrees'],
      dtype='object')

In [68]:
df.describe()

Temperature   DewPoint   Humidity  Sea Level PressureIn  \
count    31.000000  31.000000  31.000000             31.000000   
mean     34.677419  17.838710  51.677419             29.992903   
std       7.639315  11.378626  11.634395              0.237237   
min      20.000000  -3.000000  33.000000             29.520000   
25%      29.000000  10.000000  44.500000             29.855000   
50%      35.000000  18.000000  50.000000             30.010000   
75%      39.500000  23.000000  55.000000             30.140000   
max      50.000000  46.000000  78.000000             30.570000   

       VisibilityMiles  WindSpeedMPH  CloudCover  WindDirDegrees  
count        31.000000     28.000000   31.000000       31.000000  
mean          9.193548      6.892857    3.129032      247.129032  
std           1.939405      2.871821    2.629853       92.308086  
min           1.000000      2.000000    0.000000       34.000000  
25%           9.000000      5.000000    1.000000      238.000000  
50%          10.000000      6.500000    3.000000      281.000000  
75%          10.000000      8.000000    4.500000      300.000000  
max          10.000000     16.000000    8.000000      345.000000

In [63]:
#get the maximum temparature
df['Temperature'].max()

50

In [81]:
#get the minimum temperature
df['Temperature'].min()

20

In [82]:
df['Temperature'].describe()

count    31.000000
mean     34.677419
std       7.639315
min      20.000000
25%      29.000000
50%      35.000000
75%      39.500000
max      50.000000
Name: Temperature, dtype: float64

In [64]:
#to know which day it rains
df['EST'][df['Events'] == 'Rain']

8      1/9/2016
9     1/10/2016
15    1/16/2016
26    1/27/2016
Name: EST, dtype: object

In [65]:
#3. average wind speed
df['WindSpeedMPH'].mean()

6.892857142857143

In [76]:
# get all temperatures
df['Temperature']

0     38
1     36
2     40
3     25
4     20
5     33
6     39
7     39
8     44
9     50
10    33
11    35
12    26
13    30
14    43
15    47
16    36
17    25
18    22
19    32
20    31
21    26
22    26
23    28
24    34
25    43
26    41
27    37
28    36
29    34
30    46
Name: Temperature, dtype: int64

In [80]:
#get 2 or more columns
df[['DewPoint', 'Events']]

DewPoint    Events
0         23       NaN
1         18       NaN
2         21       NaN
3          9       NaN
4         -3       NaN
5          4       NaN
6         11       NaN
7         29       NaN
8         38      Rain
9         46      Rain
10         8       NaN
11        15       NaN
12         4       NaN
13        12       NaN
14        31       NaN
15        37      Rain
16        23  Fog-Snow
17         6      Snow
18         3       NaN
19        15       NaN
20        11       NaN
21         6      Snow
22        21  Fog-Snow
23        11      Snow
24        18       NaN
25        29       NaN
26        22      Rain
27        20       NaN
28        21       NaN
29        16       NaN
30        28       NaN

In [84]:
# select rows which has maximum temperature
df[df.Temperature == df.Temperature.max()]

EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
9  1/10/2016           50        46        71                 29.59   

   VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover Events  \
9                4           NaN             1.8           7   Rain   

   WindDirDegrees  
9             109

In [87]:
#select only DewPoint column which has maximum temperature
df.DewPoint[df.Temperature == df.Temperature.max()]

9    46
Name: DewPoint, dtype: int64